project: 
  type: website

website:
  site-url: https://nanoyan.github.io/p12-master/
  title: "IQB"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/nanoyan/p12-master/
  navbar: 
    logo: IQB-Klein.png
    search: true
    left:
        - href: docs/README.md
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true