name: Create new branch prepare1

on:
    workflow_dispatch:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    create-branch:
        permissions:
            contents: write
            id-token: write
        name: "Create Dynamic Branch"
        runs-on: ubuntu-latest    
        steps:
          - name: Checkout Repository  
            uses: actions/checkout@v2
          - name: Create Branch
            run: |
              git checkout -b prepare1
              git push --set-upstream origin prepare1

            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      