name: Create new branch prepare2

on:
    workflow_dispatch:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    create-branch:
        permissions:
            contents: write
            id-token: write
        name: "Create Dynamic Branch"
        runs-on: ubuntu-latest    
        steps:
          - name: Checkout Repository  
            uses: actions/checkout@v2
          - name: Create Branch
            run: |
              git config --global user.email "yanpingchenlin@gmail.com"
              git config --global user.name "nanoyan"
              git checkout -b prepare2
              rm .github/workflows/publish.yml
              git add .
              git commit -m 'delete publish yml'
              git push --set-upstream origin prepare2
              

            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      