on:
    workflow_dispatch:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

name: Prepare

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run validate
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
          retention-days: 1
          overwrite: true
      - uses: actions/checkout@v2
      - name: Rename file 
        run: mv docs/README.md index.qmd    
      - name: Create new branch
        uses: actions/checkout@v4
        with:
          repository: nanoyan/p12-master
          ref: gh-prepare
      - uses: EndBug/add-and-commit@v9

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

