on:
    workflow_dispatch:
    push:
      branches:
        - gh-prepare
    pull_request:
      branches:
        - gh-prepare

name: Validate and publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name : Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
